#!/bin/sh

DESC="Controller"
NAME=controller
CONFIG=/var/www/scraperwiki/uml/uml.cfg.local
DAEMON=/var/www/scraperwiki/uml/controller/controller.py
DAEMON_PATH=/var/www/scraperwiki/scraperlibs/
DAEMON_ARGS="--daemon --subproc --addPath=$DAEMON_PATH --varDir=./var --firewall=none --config=$CONFIG --nosetuid"
PIDFILE=./var/run/$NAME.pid

do_start()
{
	mkdir -p ./var/run
	mkdir -p ./var/log
	$DAEMON $DAEMON_ARGS
}

do_stop()
{
	[ -f $PIDFILE ] && {
		kill -TERM `cat $PIDFILE`
		rm -f $PIDFILE
		}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
  	do_stop
  	do_start
	;;
  *)
	echo "Usage: orbited {start|stop|restart}" >&2
	;;
esac
