#!/bin/sh

DESC="WebProxy"
NAME=webproxy
DAEMON=/var/www/scraperwiki/uml/httpproxy/webproxy.py
VARDIR=/var/www/scraperwiki/uml/var
CONFIG=/var/www/scraperwiki/uml/uml.cfg
PIDFILE=$VARDIR/run/$NAME.pid
DAEMON_ARGS="--pidfile=$PIDFILE --config=$CONFIG"

do_start()
{
	mkdir -p ./var/run
	mkdir -p ./var/log
	$DAEMON $DAEMON_ARGS
}

do_stop()
{
	[ -f $PIDFILE ] && {
		kill -TERM `cat $PIDFILE`
		rm -f $PIDFILE
		}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
  	do_stop
  	do_start
	;;
  *)
	echo "Usage: orbited {start|stop|restart}" >&2
	;;
esac
