#!/bin/bash
#
#  Support script to help adding packages. Unpacks an image tarball, chroots
#  a shell in it (whence installation can be performed), then packs a new
#  tarball. The two script arguments are an existing tarball and the name of
#  a new tarball.
#
test $# = 2 ||
{
	echo	usage: srce dest 
	exit	1
}

test `id -u` = 0 ||
{
	echo	addpkg: must be run as root
	exit	1
}

srce=$1
dest=$2

test "$1" = "$2" &&
{
	echo	addpkg: srce and dest must be different
	exit	1
}

test -f "$1" ||
{
	echo	addpkg: srce does not exist
	exit	1
}

test -f "$2" &&
{
	echo	addpkg: dest already exists
	exit	1
}

rm	-rf	jaunty/*

echo	Unpacking source tarball, please wait ....
tar	-xjf	$srce

cp	/etc/resolv.conf jaunty/etc

chroot	jaunty

echo	Creating destination tarball, please wait ....
tar	-cjf	$dest	jaunty
exit
rm	-rf	jaunty/*
