#!/bin/bash
#
# cloneuml
#
# Clone a UML. Takes one argument which should be the name of a UML in the
# uml.cfg file.
#
test $# = 1 ||
{
	echo	usage: cloneuml name
	exit	1
}

test `id -u` = 0 ||
{
	echo	cloneuml: must be run as root
	exit	1
}

unm=$1

get(){
	sed -n "/^\[${unm}\]/,/^\[/ s/^[ \t]*${1}[ \t]*=[ \t]*\(.*\)/\1/ p" uml.cfg.mike
}

 tap=`get tap `
 eth=`get eth `
 via=`get via `
port=`get port`

 net=`echo $eth | sed 's/[0-9]*$/0/'`

#  Check for required settings
#
test "$eth" = '' &&
{
	echo	cloneuml: no eth address: does the UML exist
	exit	1
}
test "$tap" = '' &&
{
	echo	cloneuml: no tap address: does the UML exist
	exit	1
}
test "$via" = '' &&
{
	echo	cloneuml: no via port: does the UML exist
	exit	1
}
test "$port" = '' &&
{
	echo	cloneuml: no controller port: does the UML exist
	exit	1
}

#  Check if UML aleady exists
#
test -e ${unm} &&
{
	echo	cloneuml: uml ${unm} already exists
	exit	1
}

#  Create UML directory, and create and format image to be mounted
#  on /addr in the UML instance. This image contains the UML instance
#  specific configuration.
#
mkdir	${unm}
dd 	if=/dev/zero of=${unm}/addr.img bs=1024 seek=100 count=1
mke2fs	-F ${unm}/addr.img

mkdir	-p mnt
mount	-o loop ${unm}/addr.img mnt

#  The network interfaces file is created to bring up a network
#  connection on the appropriate fixed IP address.
#
sed	-e "s/%{eth}/${eth}/"	\
	-e "s/%{net}/${net}/"	\
	-e "s/%{tap}/${tap}/"	template/interfaces > mnt/interfaces

#  The xinetd file is created to allow port-based routing from the
#  outside world to the controller rulling in the UML
#
sed	-e "s/%{unm}/${unm}/"	\
	-e "s/%{eth}/${eth}/"	\
	-e "s/%{port}/${port}/"	\
	-e "s/%{via}/${via}/"	template/xinetd > ${unm}/xinetd


#  The resolve.conf file has a joke domain name, but uses the
#  same nameserver as the host.
#
(
	echo	domain scraperwiki.net
	grep 	nameserver /etc/resolv.conf
)	> mnt/resolv.conf

#  Copy the interfaces and resolv.conf files so they can be
#  easily eyeballed.
#
cp	mnt/interfaces	${unm}/interfaces
cp	mnt/resolv.conf	${unm}/resolv.conf

umount	mnt
