#!/bin/bash
#
#  Kill locally running servers. See the 'runlocal' command.
#
./etc/local.d/controller	stop
./etc/local.d/dataproxy		stop
./etc/local.d/dispatcher	stop
./etc/local.d/ftpproxy		stop
./etc/local.d/httpproxy		stop
./etc/local.d/orbited		stop
./etc/local.d/twister		stop
