#!/bin/bash
#
#  Assemble files into the disk image that is mounted on /scraperwiki inside
#  the UML. Arguments are hostfs mounts in the form umldir:hostdir; note that
#  these are should be mounted within the /scraperwiki directory in the UML.
#
test $# -ge 1 ||
{
	echo	usage: mkscraper mount ....
	exit	1
}

MOUNTS=$*

test `id -u` = 0 ||
{
	echo	mkscraper: must be run as root
	exit	1
}

[ -e scraper.img ] && {
	echo	"mkscriper: scraper.img already exists"
	exit	1
}

rm	-f scraper.img
dd	if=/dev/zero of=scraper.img bs=1024 seek=$[ 1024 * 1024 ] count=1
mke2fs	-F scraper.img
mkdir	-p mnt
mount	-o loop scraper.img mnt

mkdir	-p mnt/etc/init.d

sed	\
	-e "s?__MOUNTS__?${MOUNTS}?" 			\
		template/scraperwiki > mnt/etc/init.d/scraperwiki
cp	etc/init.d/controller mnt/etc/init.d/controller

chmod	+x mnt/etc/init.d/scraperwiki
chmod	+x mnt/etc/init.d/controller

for mount in ${MOUNTS}
do
echo	mkdir -p        mnt/`echo $mount | sed 's/\/[^\/]*\/\(.*\):\(.*\)/\1/'`
	mkdir -p        mnt/`echo $mount | sed 's/\/[^\/]*\/\(.*\):\(.*\)/\1/'`
done

umount	mnt

# Remove any scraper.cow files. Don't bother to warn as /scraper is mounted
# read-only so nothing changes.
#
rm	-f	uml???/scraper.cow
