#!/bin/bash
#
#  Run the dispatcher, proxy, firebox and controller servers locally, .ie.,
#  without using a real UML
#
mkdir -p ./var/log
mkdir -p ./var/run

./etc/local.d/controller	restart
./etc/local.d/dataproxy		restart
./etc/local.d/dispatcher	restart
./etc/local.d/ftpproxy		restart
./etc/local.d/httpproxy		restart
./etc/local.d/httpsproxy	restart
./etc/local.d/webproxy		restart
./etc/local.d/twister		restart
./etc/local.d/orbited		restart
